[package]
authors = ["Aaron Housh <dispersias@gmail.com>"]
edition = "2018"
name = "ember_server"
version = "0.1.0"

[dependencies]
bevy = "0.2"
bevy_prototype_networking_laminar = {git = "https://github.com/Dispersia/bevy_prototype_networking_laminar", branch = "main"}
log = "0.4"
